### ISSUE TITLE
404 - No Such Resource

### ISSUE THREAD

**Issue by KimFu2** [my8100/logparser#1]
我有启动了logparser
root        47  0.0  0.0 136092 28764 pts/1    S+   Mar19   0:05 /usr/local/bin/python /usr/local/bin/logparser
root        88  0.1  0.0 136104 31992 pts/2    S    06:12   0:00 /usr/local/bin/python /usr/local/bin/logparser
但是我请求它给的链接，提示No such Resource
我进入目录看，有看到stats.json的文件
![image](https://user-images.githubusercontent.com/47135958/54736207-054c6f00-4be5-11e9-9d52-83c0225d9d0b.png)

**Comment by my8100** [comment]
Which url did you make request to? Is Scrapyd running? Is `/root/logs` where Scrapyd stores log files of Scrapy?

**Comment by KimFu2** [comment]
> Which url did you make request to? Is Scrapyd running? Is `/root/logs` where Scrapyd stores log files of Scrapy?

thx，i get it.
