### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by sulthonzh** [my8100/logparser#5]
Very often get the following error:

![image](https://user-images.githubusercontent.com/4921059/59674898-5ec93780-91ee-11e9-92f1-5d43f3ccd269.png)

**Comment by my8100** [comment]
Logparser would parse Scrapy log files periodically and incrementally,
so there's no need to worry about the file size of your log file.
The screenshot shows that MemoryError occurred when saving the parsed result,
use the `top` command to check the free RAM of your server instead.
https://github.com/my8100/logparser/blob/c2cff79af45fde303d9a8a254cf3f2cc727a626d/logparser/settings.py#L70-L72

**Comment by my8100** [comment]
Add `self.logger.error(sys.getsizeof(data))` before the code below
to show the size of *data* object in bytes
https://github.com/my8100/logparser/blob/c2cff79af45fde303d9a8a254cf3f2cc727a626d/logparser/logparser.py#L464

**Comment by sulthonzh** [comment]
i just created PR for this https://github.com/my8100/logparser/pull/6

**Comment by my8100** [comment]
Could you share the free RAM and the data size?

**Comment by sulthonzh** [comment]
File size:
![image](https://user-images.githubusercontent.com/4921059/59700636-eda17880-921d-11e9-92c4-88e4c6b17ea0.png)
Free RAM:
![image](https://user-images.githubusercontent.com/4921059/59700609-dbbfd580-921d-11e9-9419-44090d532b91.png)

**Comment by my8100** [comment]
The key is the data size (json file) when parsing the log file,
but not the log file itself.

**Comment by my8100** [comment]
Could you post the content of the *settings.py* file?

**Comment by sulthonzh** [comment]
![image](https://user-images.githubusercontent.com/4921059/59701892-c0a29500-9220-11e9-9c05-0a40fbd625fa.png)
this is my settings.py
im using default settings.py

**Comment by my8100** [comment]
Marked wontix as it's not a common case.
See https://github.com/my8100/logparser/pull/6#issuecomment-503409528 for more info.

**Comment by my8100** [comment]
Added `LOG_CATEGORIES_LIMIT` option in https://github.com/my8100/logparser/commit/349613ef7885bcfeaa94235f527e51f3be0db7dc
```
# Keep only the last N logs of each item (e.g. critical_logs) in log_categories.
# The default is 10, set it to 0 to keep all.
LOG_CATEGORIES_LIMIT = 10
```

**Comment by my8100** [comment]
@sulthonzh 
1. `pip install -U git+https://github.com/my8100/logparser.git`
2. Update `LOG_CATEGORIES_LIMIT` in the config file.
