### ISSUE TITLE
LogParser High CPU Usage

### ISSUE THREAD

**Issue by aysark** [my8100/logparser#7]
Why does LogParser use up 100% of CPU all the time?  This definitely shouldn't be needed.  I have it running a vanilla build of scrapydweb with logparser and not running any jobs or anything and LogParser uses 100% all the time for days on...

**Comment by my8100** [comment]
What’ the value of PARSE_ROUND_INTERVAL?

**Comment by my8100** [comment]
Are there a lot of log files in SCRAPYD_LOGS_DIR?
LogParser would parse the existing log files
if they are not parsed yet.

**Comment by my8100** [comment]
@aysark 
Could you share the logs of LogParser, as well as the screenshot of the CPU usage?
